import React, { useState, useEffect } from 'react';
import { Sparkles, FileText, Download, X, CheckCircle2, AlertTriangle, ShieldAlert, BarChart3, Compass, Award, Activity } from 'lucide-react';

export default function ExecutiveSummaryModal({ isOpen, onClose, profileData, activeResult }) {
  const [summary, setSummary] = useState(null);
  const [report, setReport] = useState(null);
  const [activeTab, setActiveTab] = useState('summary'); // 'summary' | 'report'
  const [isLoading, setIsLoading] = useState(false);

  useEffect(() => {
    if (isOpen && profileData) {
      loadExecutiveData();
    }
  }, [isOpen, profileData, activeResult]);

  const loadExecutiveData = async () => {
    setIsLoading(true);
    try {
      const summaryRes = await fetch('/api/analysis/executive-summary', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          profile: profileData,
          qualitySummary: profileData.qualitySummary,
          insights: profileData.insights,
          executionResult: activeResult?.execution
        })
      });
      const summaryData = await summaryRes.json();
      if (summaryData.success) {
        setSummary(summaryData.executiveSummary);
      }

      const reportRes = await fetch('/api/analysis/report', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          profile: profileData,
          qualitySummary: profileData.qualitySummary,
          insights: profileData.insights,
          executionResult: activeResult?.execution,
          question: activeResult?.question
        })
      });
      const reportData = await reportRes.json();
      if (reportData.success) {
        setReport(reportData.report);
      }
    } catch (err) {
      console.error('Failed to load executive summary data:', err);
    } finally {
      setIsLoading(false);
    }
  };

  const downloadMarkdownReport = () => {
    if (!report) return;

    let md = `# ${report.title}\n`;
    md += `*Generated by PSA01 Verifiable Analytics Engine on ${new Date(report.timestamp).toLocaleString()}*\n\n`;

    md += `## 1. Executive Summary\n`;
    md += `- **Performance**: ${report.executiveSummary.performance}\n`;
    md += `- **Trend Status**: ${report.executiveSummary.trend}\n`;
    md += `- **Data Quality Status**: ${report.executiveSummary.dataQuality.status} (${report.executiveSummary.dataQuality.message})\n`;
    md += `- **Statistical Outliers**: ${report.executiveSummary.statisticalOutliers}\n`;
    md += `- **Forecast Trajectory**: ${report.executiveSummary.forecast}\n`;
    md += `- **Key Finding**: ${report.executiveSummary.keyFinding}\n`;
    md += `- **Recommended Action**: ${report.executiveSummary.recommendedAction}\n\n`;

    md += `## 2. Dataset Schema & Ingestion Overview\n`;
    md += `- Total Records: ${report.datasetOverview.rowCount.toLocaleString()}\n`;
    md += `- Total Columns: ${report.datasetOverview.columnCount}\n\n`;
    md += `| Column | Data Type | Semantic Type | Missing | Outliers | Status |\n`;
    md += `| --- | --- | --- | --- | --- | --- |\n`;
    report.datasetOverview.schema.forEach(col => {
      md += `| ${col.name} | ${col.type} | ${col.semanticType} | ${col.missingCount} | ${col.outliers} | ${col.status} |\n`;
    });
    md += `\n`;

    md += `## 3. Data Quality & Audit\n`;
    md += `- Overall Status: ${report.dataQualityAudit.overallStatus}\n`;
    md += `- Missing Values: ${report.dataQualityAudit.missingValuesCount}\n`;
    md += `- Duplicate Rows: ${report.dataQualityAudit.duplicateRowsCount}\n`;
    md += `- IQR Statistical Outliers: ${report.dataQualityAudit.statisticalOutliersCount}\n\n`;

    if (report.analyticalFindings) {
      md += `## 4. Analytical Findings (${report.analyticalFindings.operation.toUpperCase()})\n`;
      md += `**Query:** "${report.analyticalFindings.question}"\n\n`;
      md += `**Finding:** ${report.analyticalFindings.finding}\n\n`;
      md += `**Evidence:**\n`;
      report.analyticalFindings.evidence.forEach(ev => {
        md += `- ${ev}\n`;
      });
      md += `\n`;
    }

    md += `## 5. Recommendations & Decision Support\n`;
    report.recommendations.forEach(rec => {
      md += `### ${rec.title}\n`;
      md += `${rec.action}\n`;
      md += `*Note: ${rec.evidenceNote}*\n\n`;
    });

    if (report.disclaimers && report.disclaimers.length > 0) {
      md += `## 6. Disclaimers & Boundaries\n`;
      report.disclaimers.forEach(d => md += `- ${d}\n`);
      md += `\n`;
    }

    md += `## 7. Traceability Matrix\n`;
    md += `- **Calculated Results**: ${report.traceabilityMatrix.calculatedResults}\n`;
    md += `- **AI Interpretations**: ${report.traceabilityMatrix.aiInterpretations}\n`;
    md += `- **Data Integrity**: ${report.traceabilityMatrix.dataIntegrity}\n`;

    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `PSA01_Analysis_Report_${Date.now()}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  if (!isOpen) return null;

  return (
    <div style={{
      position: 'fixed',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      background: 'rgba(0,0,0,0.7)',
      backdropFilter: 'blur(6px)',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      zIndex: 99999,
      padding: '1.5rem'
    }}>
      <div style={{
        background: 'var(--bg-surface)',
        border: '1px solid var(--border-color)',
        borderRadius: 'var(--radius-lg)',
        width: '100%',
        maxWidth: '850px',
        maxHeight: '90vh',
        display: 'flex',
        flexDirection: 'column',
        boxShadow: '0 20px 60px rgba(0,0,0,0.4)',
        overflow: 'hidden'
      }}>
        {/* Modal Header */}
        <div style={{
          padding: '1.25rem 1.5rem',
          borderBottom: '1px solid var(--border-color)',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          background: 'var(--bg-app)'
        }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '0.6rem' }}>
            <FileText size={22} style={{ color: 'var(--primary)' }} />
            <h3 style={{ margin: 0, fontSize: '1.2rem', fontWeight: 800, color: 'var(--text-main)' }}>
              Phase 15 Decision Support & Analysis Report
            </h3>
          </div>
          <button onClick={onClose} style={{ background: 'none', border: 'none', color: 'var(--text-muted)', cursor: 'pointer', padding: '0.3rem' }}>
            <X size={20} />
          </button>
        </div>

        {/* Modal Nav Tabs */}
        <div style={{ display: 'flex', gap: '0.5rem', padding: '0.75rem 1.5rem', borderBottom: '1px solid var(--border-color)', background: 'var(--bg-surface)' }}>
          <button
            onClick={() => setActiveTab('summary')}
            style={{
              background: activeTab === 'summary' ? 'var(--primary-glow)' : 'transparent',
              color: activeTab === 'summary' ? 'var(--primary)' : 'var(--text-muted)',
              border: activeTab === 'summary' ? '1px solid var(--border-active)' : '1px solid transparent',
              padding: '0.45rem 1rem',
              borderRadius: 'var(--radius-sm)',
              fontSize: '0.85rem',
              fontWeight: 700,
              cursor: 'pointer',
              display: 'flex',
              alignItems: 'center',
              gap: '0.4rem'
            }}
          >
            <Compass size={15} /> Executive Summary
          </button>
          <button
            onClick={() => setActiveTab('report')}
            style={{
              background: activeTab === 'report' ? 'var(--primary-glow)' : 'transparent',
              color: activeTab === 'report' ? 'var(--secondary)' : 'var(--text-muted)',
              border: activeTab === 'report' ? '1px solid var(--border-active)' : '1px solid transparent',
              padding: '0.45rem 1rem',
              borderRadius: 'var(--radius-sm)',
              fontSize: '0.85rem',
              fontWeight: 700,
              cursor: 'pointer',
              display: 'flex',
              alignItems: 'center',
              gap: '0.4rem'
            }}
          >
            <FileText size={15} /> Detailed Analysis Report
          </button>
        </div>

        {/* Modal Content Body */}
        <div style={{ padding: '1.5rem', overflowY: 'auto', flex: 1 }}>
          {isLoading ? (
            <div style={{ textAlign: 'center', padding: '3rem' }}>
              <div className="spinner" style={{ margin: '0 auto 1rem auto' }} />
              <p style={{ color: 'var(--text-muted)', fontSize: '0.9rem' }}>Compiling Executive Summary and Verifiable Report...</p>
            </div>
          ) : (
            activeTab === 'summary' ? (
              summary && (
                <div style={{ display: 'flex', flexDirection: 'column', gap: '1.25rem' }}>
                  
                  {/* Status Banner */}
                  <div style={{
                    background: summary.dataQuality.status === 'CLEAN' ? 'rgba(16, 185, 129, 0.08)' : summary.dataQuality.status === 'CRITICAL' ? 'rgba(244, 63, 94, 0.08)' : 'rgba(245, 158, 11, 0.08)',
                    border: summary.dataQuality.status === 'CLEAN' ? '1px solid rgba(16, 185, 129, 0.3)' : summary.dataQuality.status === 'CRITICAL' ? '1px solid rgba(244, 63, 94, 0.3)' : '1px solid rgba(245, 158, 11, 0.3)',
                    borderRadius: 'var(--radius-md)',
                    padding: '1rem 1.25rem',
                    display: 'flex',
                    alignItems: 'center',
                    gap: '1rem'
                  }}>
                    {summary.dataQuality.status === 'CLEAN' ? (
                      <CheckCircle2 size={32} style={{ color: 'var(--accent-emerald)', flexShrink: 0 }} />
                    ) : summary.dataQuality.status === 'CRITICAL' ? (
                      <ShieldAlert size={32} style={{ color: 'var(--accent-rose)', flexShrink: 0 }} />
                    ) : (
                      <AlertTriangle size={32} style={{ color: 'var(--accent-amber)', flexShrink: 0 }} />
                    )}
                    <div>
                      <div style={{ fontWeight: 800, fontSize: '1rem', color: 'var(--text-main)', marginBottom: '0.2rem' }}>
                        Data Quality Status: {summary.dataQuality.status}
                      </div>
                      <p style={{ margin: 0, fontSize: '0.88rem', color: 'var(--text-muted)' }}>
                        {summary.dataQuality.message}
                      </p>
                    </div>
                  </div>

                  {/* Overview Grid */}
                  <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: '1rem' }}>
                    <div className="summary-card">
                      <div className="summary-card-title">Dataset Performance</div>
                      <div style={{ fontSize: '0.9rem', fontWeight: 700, color: 'var(--text-main)', marginTop: '0.3rem' }}>
                        {summary.performance}
                      </div>
                    </div>

                    <div className="summary-card">
                      <div className="summary-card-title">Overall Trend</div>
                      <div style={{ fontSize: '0.9rem', fontWeight: 700, color: 'var(--primary)', marginTop: '0.3rem' }}>
                        {summary.trend}
                      </div>
                    </div>

                    <div className="summary-card">
                      <div className="summary-card-title">IQR Outliers</div>
                      <div style={{ fontSize: '0.9rem', fontWeight: 700, color: 'var(--accent-amber)', marginTop: '0.3rem' }}>
                        {summary.statisticalOutliers}
                      </div>
                    </div>
                  </div>

                  {/* Key Finding */}
                  <div style={{ background: 'var(--bg-app)', border: '1px solid var(--border-color)', borderRadius: 'var(--radius-md)', padding: '1.25rem' }}>
                    <div style={{ fontSize: '0.78rem', fontWeight: 800, textTransform: 'uppercase', color: 'var(--text-dim)', marginBottom: '0.4rem' }}>
                      Key Verified Finding
                    </div>
                    <p style={{ margin: 0, fontSize: '0.95rem', fontWeight: 700, color: 'var(--text-main)', lineHeight: '1.5' }}>
                      {summary.keyFinding}
                    </p>
                  </div>

                  {/* Recommended Action */}
                  <div style={{ background: 'rgba(99, 102, 241, 0.08)', border: '1px solid rgba(99, 102, 241, 0.25)', borderRadius: 'var(--radius-md)', padding: '1.25rem' }}>
                    <div style={{ fontSize: '0.78rem', fontWeight: 800, textTransform: 'uppercase', color: 'var(--primary)', marginBottom: '0.4rem', display: 'flex', alignItems: 'center', gap: '0.4rem' }}>
                      <Award size={15} /> Recommended Action
                    </div>
                    <p style={{ margin: 0, fontSize: '0.92rem', color: 'var(--text-main)', lineHeight: '1.55', fontWeight: 600 }}>
                      {summary.recommendedAction}
                    </p>
                  </div>

                </div>
              )
            ) : (
              report && (
                <div style={{ fontFamily: 'var(--font-sans)', fontSize: '0.88rem', color: 'var(--text-main)', lineHeight: '1.6' }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.5rem', borderBottom: '1px solid var(--border-color)', paddingBottom: '0.85rem' }}>
                    <div>
                      <h4 style={{ margin: 0, fontSize: '1.1rem', fontWeight: 800 }}>{report.title}</h4>
                      <span style={{ fontSize: '0.78rem', color: 'var(--text-dim)' }}>PSA01 Deterministic Report Matrix</span>
                    </div>
                    <button className="btn btn-primary" onClick={downloadMarkdownReport} style={{ fontSize: '0.82rem' }}>
                      <Download size={14} /> Download Markdown (.md)
                    </button>
                  </div>

                  <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
                    <section>
                      <h5 style={{ fontSize: '0.95rem', fontWeight: 800, color: 'var(--primary)', marginBottom: '0.5rem' }}>1. Executive Summary</h5>
                      <ul style={{ margin: 0, paddingLeft: '1.2rem' }}>
                        <li><strong>Performance:</strong> {report.executiveSummary.performance}</li>
                        <li><strong>Trend:</strong> {report.executiveSummary.trend}</li>
                        <li><strong>Data Quality:</strong> {report.executiveSummary.dataQuality.status} ({report.executiveSummary.dataQuality.message})</li>
                        <li><strong>Outliers:</strong> {report.executiveSummary.statisticalOutliers}</li>
                        <li><strong>Key Finding:</strong> {report.executiveSummary.keyFinding}</li>
                      </ul>
                    </section>

                    <section>
                      <h5 style={{ fontSize: '0.95rem', fontWeight: 800, color: 'var(--primary)', marginBottom: '0.5rem' }}>2. Data Quality & Audit</h5>
                      <p style={{ margin: 0 }}>
                        Dataset contains {report.datasetOverview.rowCount.toLocaleString()} rows and {report.datasetOverview.columnCount} columns. Total missing values: {report.dataQualityAudit.missingValuesCount}, duplicates: {report.dataQualityAudit.duplicateRowsCount}, statistical IQR outliers: {report.dataQualityAudit.statisticalOutliersCount}.
                      </p>
                    </section>

                    {report.analyticalFindings && (
                      <section style={{ background: 'var(--bg-app)', padding: '1rem', borderRadius: 'var(--radius-sm)', border: '1px solid var(--border-color)' }}>
                        <h5 style={{ fontSize: '0.95rem', fontWeight: 800, color: 'var(--accent-cyan)', margin: '0 0 0.5rem 0' }}>
                          3. Analytical Findings ({report.analyticalFindings.operation.toUpperCase()})
                        </h5>
                        <p style={{ fontWeight: 700, margin: '0 0 0.5rem 0' }}>"{report.analyticalFindings.question}"</p>
                        <p style={{ margin: '0 0 0.5rem 0' }}>{report.analyticalFindings.finding}</p>
                        <ul style={{ margin: 0, paddingLeft: '1.2rem', fontSize: '0.84rem' }}>
                          {report.analyticalFindings.evidence.map((ev, i) => <li key={i}>{ev}</li>)}
                        </ul>
                      </section>
                    )}

                    <section>
                      <h5 style={{ fontSize: '0.95rem', fontWeight: 800, color: 'var(--primary)', marginBottom: '0.5rem' }}>4. Recommendations</h5>
                      {report.recommendations.map((rec, i) => (
                        <div key={i} style={{ marginBottom: '0.75rem' }}>
                          <strong>{rec.title}:</strong> {rec.action}
                        </div>
                      ))}
                    </section>

                    <section style={{ borderTop: '1px dashed var(--border-color)', paddingTop: '0.75rem', fontSize: '0.78rem', color: 'var(--text-dim)' }}>
                      <strong>Traceability Matrix:</strong> Calculated Results derived 100% deterministically by Phase 3 Engine. AI explanations are strictly evidence-grounded.
                    </section>
                  </div>
                </div>
              )
            )
          )}
        </div>

        {/* Modal Footer */}
        <div style={{ padding: '1rem 1.5rem', borderTop: '1px solid var(--border-color)', background: 'var(--bg-app)', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <span style={{ fontSize: '0.78rem', color: 'var(--text-dim)' }}>PSA01 System Phase 15 Integration</span>
          <div style={{ display: 'flex', gap: '0.6rem' }}>
            {report && (
              <button className="btn btn-secondary" onClick={downloadMarkdownReport} style={{ fontSize: '0.82rem' }}>
                <Download size={14} /> Download Report
              </button>
            )}
            <button className="btn btn-primary" onClick={onClose} style={{ fontSize: '0.82rem' }}>
              Close
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
